name: Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Build Targets"
        required: true
        default: "both"
        type: choice
        options:
          - both
          - windows-x64
          - linux-aarch64

jobs:
  build-windows-x64:
    if: ${{ github.event.inputs.target == 'both' || github.event.inputs.target == 'windows-x64' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .venv\Scripts\pip install --upgrade pip
          .venv\Scripts\pip install pygame pyside6 dbus-next pyinstaller

      - name: Run build.py
        shell: pwsh
        env:
          PYTHONUTF8: "1"
        run: .venv\Scripts\python build.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-windows-x64
          path: release/windows-x64/
          retention-days: 30

  build-linux-aarch64:
    if: ${{ github.event.inputs.target == 'both' || github.event.inputs.target == 'linux-aarch64' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pygame pyside6 dbus-next pyinstaller

      - name: Warning before building for Linux ARM
        run: echo "WARNING: This build artifact is not intended for execution on Raspberry Pi devices. Please do not run the generated executable on Raspberry Pi."

      - name: Run build.py
        run: .venv/bin/python build.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-linux-aarch64
          path: release/linux-aarch64/
          retention-days: 30
