name: Build (PyInstaller)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Build Targets (PyInstaller)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - windows-x64
          - linux-24-aarch64
          - linux-x64

jobs:
  build-windows-x64:
    if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'windows-x64' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .venv\Scripts\pip install --upgrade pip
          .venv\Scripts\pip install pygame pyside6 dbus-next pyinstaller

      - name: Run build-pyinstaller.py
        shell: pwsh
        env:
          PYTHONUTF8: "1"
        run: .venv\Scripts\python build-pyinstaller.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-windows-x64
          path: release/windows-x64/
          retention-days: 30

  build-ubuntu-24-arch64:
    if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'linux-aarch64' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pygame pyside6 dbus-next pyinstaller

      - name: Run build-pyinstaller.py
        run: .venv/bin/python build-pyinstaller.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-ubuntu-24-aarch64
          path: release/ubuntu-24-aarch64/
          retention-days: 30

  build-ubuntu-24-x64:
    if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'linux-x64' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pygame pyside6 dbus-next pyinstaller

      - name: Run build-pyinstaller.py
        run: .venv/bin/python build-pyinstaller.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-ubunt-24-x64
          path: release/ubuntu-24-x64/
          retention-days: 30

  build-ubuntu-26-x64:
    if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'linux-x64' }}
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Creating a venv and Installing Dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pygame pyside6 dbus-next pyinstaller

      - name: Run build-pyinstaller.py
        run: .venv/bin/python build-pyinstaller.py

      - uses: actions/upload-artifact@v5
        with:
          name: RemoteINDIPAD-ubuntu-26-x64
          path: release/ubuntu-26-x64/
          retention-days: 30
